# Generated by Django 5.0.4 on 2024-04-17 07:23

import django.core.validators
import django_basics_retake.profiles.profile_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(2), django_basics_retake.profiles.profile_validators.validate_username], verbose_name='Nickname')),
                ('first_name', models.CharField(max_length=30, validators=[django_basics_retake.profiles.profile_validators.validate_name], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, validators=[django_basics_retake.profiles.profile_validators.validate_name], verbose_name='Last Name')),
                ('chef', models.BooleanField(default=False, verbose_name='Chef')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
            ],
        ),
    ]
